[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "src/functions"
  included_files = ["node_modules/chrome-aws-lambda/**"]
  node_bundler = "esbuild"

[functions.keyword]
  timeout = 30

[functions.related-keywords]
  timeout = 30 