[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "src/functions"
  included_files = ["node_modules/chrome-aws-lambda/**"]
  node_bundler = "esbuild"

[functions.keyword]
  timeout = 30

[functions.related-keywords]
  timeout = 30

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" 